on:
  push:
    branches:
      - develop
      - release/**
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
  
env:
  NODE_VERSION: '16'

concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Test Flow
jobs:
  job01:
    name: Job 01
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: ./run.sh 5 0 
